Dockerfile: pin Bundler 2.3.26 for Ruby 2.5 support
Step 9/13 : RUN gem install bundler
 ---> Running in cbe3dbb35305
ERROR:  Error installing bundler:
        The last version of bundler (>= 0) to support your Ruby & RubyGems was 2.3.26. Try installing it with `gem install bundler -v 2.3.26`
        bundler requires Ruby version >= 2.6.0. The current ruby version is 2.5.0.